test = [{'id': 0, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 8, 'pos_x': 13, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 1, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 8, 'pos_x': 13, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 2, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 11, 'pos_x': 17, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 3, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 12, 'pos_x': 13, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 4, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 9, 'pos_x': 9, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 5, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 12, 'pos_x': 13, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 6, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 4, 'pos_x': 12, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 7, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 12, 'pos_x': 11, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 8, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 14, 'pos_x': 15, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 9, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 5, 'pos_x': 
13, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 10, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 7, 'pos_x': 10, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 11, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 7, 'pos_x': 9, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 12, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 16, 'pos_x': 15, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 13, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 8, 'pos_x': 18, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 14, 'team': 2, 'health': 3, 
'level': 1, 'pos_y': 8, 'pos_x': 10, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 15, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 1, 'pos_x': 18, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 16, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 14, 'pos_x': 15, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 17, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 4, 'pos_x': 5, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 18, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 8, 'pos_x': 16, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 19, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 8, 'pos_x': 16, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 20, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 3, 'pos_x': 13, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 21, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 0, 'pos_x': 18, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 22, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 13, 'pos_x': 16, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 23, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 12, 'pos_x': 11, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 24, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 6, 'pos_x': 7, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 25, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 7, 'pos_x': 5, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 26, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 8, 'pos_x': 18, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 27, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 10, 'pos_x': 10, 'carrying': True, 'clod_force': 1, 'played': False}, {'id': 28, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 13, 'pos_x': 17, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 29, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 9, 'pos_x': 16, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 30, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 9, 'pos_x': 15, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 31, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 7, 'pos_x': 9, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 32, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 5, 'pos_x': 19, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 33, 'team': 2, 'health': 3, 
'level': 1, 'pos_y': 11, 'pos_x': 14, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 34, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 7, 'pos_x': 6, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 35, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 13, 'pos_x': 11, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 36, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 15, 'pos_x': 6, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 37, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 12, 'pos_x': 13, 'carrying': False, 'clod_force': None, 'played': False}, 
{'id': 38, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 0, 'pos_x': 12, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 39, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 8, 'pos_x': 7, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 40, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 8, 'pos_x': 14, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 41, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 11, 'pos_x': 9, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 42, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 11, 'pos_x': 11, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 43, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 6, 'pos_x': 17, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 44, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 6, 'pos_x': 9, 'carrying': True, 'clod_force': 1, 'played': False}, {'id': 45, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 4, 'pos_x': 9, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 46, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 0, 'pos_x': 7, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 47, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 12, 'pos_x': 15, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 48, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 4, 'pos_x': 8, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 49, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 9, 'pos_x': 14, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 50, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 2, 'pos_x': 12, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 51, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 9, 'pos_x': 11, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 52, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 8, 'pos_x': 7, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 53, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 13, 'pos_x': 13, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 54, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 5, 'pos_x': 11, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 55, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 8, 'pos_x': 4, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 56, 'team': 2, 'health': 3, 'level': 1, 'pos_y': 12, 'pos_x': 12, 'carrying': False, 'clod_force': None, 'played': False}, {'id': 57, 'team': 1, 'health': 3, 'level': 1, 'pos_y': 8, 'pos_x': 6, 'carrying': False, 'clod_force': None, 'played': False}]

matching = []

for ant in test:
    ant_pos_y = ant['pos_y']
    ant_pos_x = ant['pos_x']
    if not (ant_pos_y, ant_pos_x) in matching:
        matching.append((ant_pos_y, ant_pos_x))
    else:
        print('match found')
        print(ant)